# _config.yml
exclude: ['./README.md']

title: "Board Game Collection"
author:
  name: Jarrod Rose
description: "A collection of board games I own and love."
baseurl: "/Board-Games" # the subpath for your site
url: "https://jarrodrose.github.io"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme # Added to allow for using Minima 3.x

# set up remote_theme to use Minima 3.x
remote_theme: jekyll/minima
#theme: minima # Default Github Theme v2.x currently


minima:
  nav_pages:
    - about.md
  skin: classic
  hide_site_feed_link: true
