# _config.yml
exclude: ['./README.md']

title: "Board Game Collection"
description: "A collection of board games I own and love."
baseurl: "/Board-Games" # the subpath for your site
url: "https://jarrodrose.github.io"

# Add to plugins: list
plugins:
  - jekyll-remote-theme

# set up remote_theme
remote_theme: jekyll/minima
#theme: minima # or another theme of your choice

author:
  name: Jarrod Rose

minima:
  nav_pages:
    - about.md
  skin: dark
